// IPMsgX/Crypto/CryptoService.swift
// Actor for RSA key management, encryption, decryption, signing
// Ported from CryptoManager.m

import Foundation
import Security
import CommonCrypto

private let keychainKeyLabel = "IP Messenger Encryption Key"
private let keychainKeyComment = "Generated by IPMsgX for macOS."

// Encryption result from encryptMessage
struct EncryptionResult: Sendable {
    let encryptedAppendix: String  // "spec:encKey:encBody[:signature]"
    let plainOptionData: Data?
    let encExtMsg: Bool
}

// Decryption result from decryptMessage
struct DecryptionResult: Sendable {
    let plainText: String
    let secureLevel: Int
    let doubt: Bool
    let optionData: Data?
}

actor CryptoService {
    private(set) var selfCapability = CryptoCapability(
        supportBlowfish128: true,
        supportAES256: true,
        supportRSA1024: true,
        supportRSA2048: true,
        supportPacketNoIV: true,
        supportEncodeBase64: true,
        supportSignSHA1: true,
        supportSignSHA256: true
    )

    private var privateKey2048: SecKey?
    private var privateKey1024: SecKey?
    private(set) var publicKey2048: (exponent: UInt32, modulus: Data)?
    private(set) var publicKey1024: (exponent: UInt32, modulus: Data)?
    private var publicSecKey2048: SecKey?
    private var publicSecKey1024: SecKey?

    // MARK: - Startup

    func startup() {
        setupKeyPair(bitSize: 2048)
        setupKeyPair(bitSize: 1024)
        selfTest()
    }

    /// Verify that encrypt/decrypt round-trips correctly for each key pair
    private func selfTest() {
        let testData = Data("IPMsgX self-test".utf8)

        if let pub2048 = publicKey2048, let _ = privateKey2048 {
            guard let secKey = RSAPublicKeyHelper.createSecKey(exponent: pub2048.exponent, modulus: pub2048.modulus) else {
                NSLog("[CRYPTO] RSA2048 self-test FAILED: could not create SecKey from extracted components (mod=%d bytes, exp=0x%X)", pub2048.modulus.count, pub2048.exponent)
                return
            }
            var error: Unmanaged<CFError>?
            guard let encrypted = SecKeyCreateEncryptedData(secKey, .rsaEncryptionPKCS1, testData as CFData, &error) as Data? else {
                NSLog("[CRYPTO] RSA2048 self-test FAILED: encryption error: %@", String(describing: error))
                return
            }
            guard let decrypted = decryptRSA(data: encrypted, keyBitSize: 2048) else {
                NSLog("[CRYPTO] RSA2048 self-test FAILED: decryption returned nil — key pair is broken! Regenerating...")
                // Delete corrupted key and regenerate
                try? FileManager.default.removeItem(at: Self.keyFilePath(bitSize: 2048))
                privateKey2048 = nil; publicKey2048 = nil; publicSecKey2048 = nil
                setupKeyPair(bitSize: 2048)
                return
            }
            if decrypted == testData {
                NSLog("[CRYPTO] RSA2048 self-test PASSED (mod=%d bytes)", pub2048.modulus.count)
            } else {
                NSLog("[CRYPTO] RSA2048 self-test FAILED: decrypted data doesn't match!")
            }
        } else {
            NSLog("[CRYPTO] RSA2048 self-test SKIPPED: key pair not available (pub=%d, priv=%d)", publicKey2048 != nil ? 1 : 0, privateKey2048 != nil ? 1 : 0)
        }

        if let pub1024 = publicKey1024, let _ = privateKey1024 {
            guard let secKey = RSAPublicKeyHelper.createSecKey(exponent: pub1024.exponent, modulus: pub1024.modulus) else {
                NSLog("[CRYPTO] RSA1024 self-test FAILED: could not create SecKey from extracted components")
                return
            }
            var error: Unmanaged<CFError>?
            guard let encrypted = SecKeyCreateEncryptedData(secKey, .rsaEncryptionPKCS1, testData as CFData, &error) as Data? else {
                NSLog("[CRYPTO] RSA1024 self-test FAILED: encryption error: %@", String(describing: error))
                return
            }
            guard let decrypted = decryptRSA(data: encrypted, keyBitSize: 1024) else {
                NSLog("[CRYPTO] RSA1024 self-test FAILED: decryption returned nil — key pair is broken! Regenerating...")
                try? FileManager.default.removeItem(at: Self.keyFilePath(bitSize: 1024))
                privateKey1024 = nil; publicKey1024 = nil; publicSecKey1024 = nil
                setupKeyPair(bitSize: 1024)
                return
            }
            if decrypted == testData {
                NSLog("[CRYPTO] RSA1024 self-test PASSED (mod=%d bytes)", pub1024.modulus.count)
            } else {
                NSLog("[CRYPTO] RSA1024 self-test FAILED: decrypted data doesn't match!")
            }
        } else {
            NSLog("[CRYPTO] RSA1024 self-test SKIPPED: key pair not available (pub=%d, priv=%d)", publicKey1024 != nil ? 1 : 0, privateKey1024 != nil ? 1 : 0)
        }
    }

    private static var keyStorageDirectory: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        return appSupport.appendingPathComponent("IPMsgX", isDirectory: true)
    }

    private static func keyFilePath(bitSize: Int) -> URL {
        keyStorageDirectory.appendingPathComponent("rsa\(bitSize)_private.key")
    }

    private func setupKeyPair(bitSize: Int) {
        NSLog("[CRYPTO] Setting up RSA%d key pair", bitSize)

        // Try to load persisted key first
        if loadPersistedKeyPair(bitSize: bitSize) {
            NSLog("[CRYPTO] RSA%d key pair loaded from disk", bitSize)
            return
        }

        // Generate new key pair
        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeRSA,
            kSecAttrKeySizeInBits as String: bitSize,
        ]

        var error: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateRandomKey(attributes as CFDictionary, &error) else {
            NSLog("[CRYPTO] SecKeyCreateRandomKey failed for RSA%d: %@", bitSize, String(describing: error))
            disableKeySize(bitSize)
            return
        }

        guard installKeyPair(privateKey: privateKey, bitSize: bitSize) else {
            disableKeySize(bitSize)
            return
        }

        // Persist to disk
        persistPrivateKey(privateKey, bitSize: bitSize)

        NSLog("[CRYPTO] RSA%d key pair generated and persisted to disk", bitSize)
    }

    /// Install a private key: extract public key and components, store in instance vars
    private func installKeyPair(privateKey: SecKey, bitSize: Int) -> Bool {
        guard let publicKey = SecKeyCopyPublicKey(privateKey) else {
            NSLog("[CRYPTO] SecKeyCopyPublicKey failed for RSA%d", bitSize)
            return false
        }

        guard let components = RSAPublicKeyHelper.extractComponents(from: publicKey) else {
            NSLog("[CRYPTO] RSA%d public key extraction failed", bitSize)
            return false
        }

        switch bitSize {
        case 2048:
            privateKey2048 = privateKey
            publicKey2048 = components
            publicSecKey2048 = publicKey
        case 1024:
            privateKey1024 = privateKey
            publicKey1024 = components
            publicSecKey1024 = publicKey
        default:
            return false
        }
        NSLog("[CRYPTO] RSA%d key pair installed (exp=0x%X, mod=%d bytes)", bitSize, components.exponent, components.modulus.count)
        return true
    }

    /// Save private key's external representation to Application Support
    private func persistPrivateKey(_ key: SecKey, bitSize: Int) {
        var error: Unmanaged<CFError>?
        guard let keyData = SecKeyCopyExternalRepresentation(key, &error) as Data? else {
            NSLog("[CRYPTO] Failed to export RSA%d private key: %@", bitSize, String(describing: error))
            return
        }

        let dir = Self.keyStorageDirectory
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let path = Self.keyFilePath(bitSize: bitSize)
        do {
            try keyData.write(to: path, options: [.atomic, .completeFileProtection])
            NSLog("[CRYPTO] RSA%d private key saved to %@", bitSize, path.path)
        } catch {
            NSLog("[CRYPTO] Failed to write RSA%d key file: %@", bitSize, error.localizedDescription)
        }
    }

    /// Load private key from persisted file
    private func loadPersistedKeyPair(bitSize: Int) -> Bool {
        let path = Self.keyFilePath(bitSize: bitSize)

        guard let keyData = try? Data(contentsOf: path) else {
            NSLog("[CRYPTO] No persisted RSA%d key at %@", bitSize, path.path)
            return false
        }

        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeRSA,
            kSecAttrKeyClass as String: kSecAttrKeyClassPrivate,
            kSecAttrKeySizeInBits as String: bitSize,
        ]

        var error: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateWithData(keyData as CFData, attributes as CFDictionary, &error) else {
            NSLog("[CRYPTO] Failed to recreate RSA%d private key from disk: %@", bitSize, String(describing: error))
            // Delete corrupt key file so a fresh key is generated next time
            try? FileManager.default.removeItem(at: path)
            return false
        }

        return installKeyPair(privateKey: privateKey, bitSize: bitSize)
    }

    private func disableKeySize(_ bitSize: Int) {
        switch bitSize {
        case 2048: selfCapability.supportRSA2048 = false
        case 1024: selfCapability.supportRSA1024 = false
        default: break
        }
    }

    // MARK: - Random Data

    func randomData(byteCount: Int) -> Data? {
        var bytes = [UInt8](repeating: 0, count: byteCount)
        let status = SecRandomCopyBytes(kSecRandomDefault, byteCount, &bytes)
        guard status == errSecSuccess else { return nil }
        return Data(bytes)
    }

    // MARK: - RSA Encrypt/Decrypt

    func encryptRSA(data: Data, recipientKey: RSAPublicKeyInfo) -> Data? {
        guard let secKey = RSAPublicKeyHelper.createSecKey(exponent: recipientKey.exponent, modulus: recipientKey.modulus) else {
            NSLog("[CRYPTO] encryptRSA: failed to create SecKey (mod=%d bytes, exp=0x%X)", recipientKey.modulus.count, recipientKey.exponent)
            return nil
        }

        var error: Unmanaged<CFError>?
        guard let encrypted = SecKeyCreateEncryptedData(
            secKey,
            .rsaEncryptionPKCS1,
            data as CFData,
            &error
        ) as Data? else {
            NSLog("[CRYPTO] RSA encrypt error: %@", String(describing: error))
            return nil
        }

        return encrypted
    }

    func decryptRSA(data: Data, keyBitSize: Int) -> Data? {
        let privateKey: SecKey?
        switch keyBitSize {
        case 2048: privateKey = privateKey2048
        case 1024: privateKey = privateKey1024
        default: return nil
        }

        guard let privateKey else {
            NSLog("[CRYPTO] RSA decrypt: no private key for %d-bit", keyBitSize)
            return nil
        }

        var error: Unmanaged<CFError>?
        guard let decrypted = SecKeyCreateDecryptedData(
            privateKey,
            .rsaEncryptionPKCS1,
            data as CFData,
            &error
        ) as Data? else {
            NSLog("[CRYPTO] RSA%d decrypt FAILED: %@", keyBitSize, String(describing: error?.takeUnretainedValue()))
            return nil
        }

        return decrypted
    }

    // MARK: - Signing

    func signSHA256(data: Data, keyBitSize: Int) -> Data? {
        sign(data: data, algorithm: .rsaSignatureMessagePKCS1v15SHA256, keyBitSize: keyBitSize)
    }

    func signSHA1(data: Data, keyBitSize: Int) -> Data? {
        sign(data: data, algorithm: .rsaSignatureMessagePKCS1v15SHA1, keyBitSize: keyBitSize)
    }

    private func sign(data: Data, algorithm: SecKeyAlgorithm, keyBitSize: Int) -> Data? {
        let privateKey: SecKey?
        switch keyBitSize {
        case 2048: privateKey = privateKey2048
        case 1024: privateKey = privateKey1024
        default: return nil
        }
        guard let privateKey else { return nil }

        var error: Unmanaged<CFError>?
        guard let signature = SecKeyCreateSignature(
            privateKey,
            algorithm,
            data as CFData,
            &error
        ) as Data? else {
            NSLog("[CRYPTO] Sign error: %@", String(describing: error))
            return nil
        }
        return signature
    }

    // MARK: - Verification

    func verifySHA256(signature: Data, data: Data, key: RSAPublicKeyInfo) -> Bool {
        verify(signature: signature, data: data, key: key, algorithm: .rsaSignatureMessagePKCS1v15SHA256)
    }

    func verifySHA1(signature: Data, data: Data, key: RSAPublicKeyInfo) -> Bool {
        verify(signature: signature, data: data, key: key, algorithm: .rsaSignatureMessagePKCS1v15SHA1)
    }

    private func verify(signature: Data, data: Data, key: RSAPublicKeyInfo, algorithm: SecKeyAlgorithm) -> Bool {
        guard let secKey = RSAPublicKeyHelper.createSecKey(exponent: key.exponent, modulus: key.modulus) else {
            return false
        }

        var error: Unmanaged<CFError>?
        return SecKeyVerifySignature(secKey, algorithm, data as CFData, signature as CFData, &error)
    }

    // MARK: - Fingerprint
    // SHA1 of reversed modulus bytes, reverse first 20 bytes, XOR three 8-byte blocks
    // Ported from CryptoManager.m:252-282

    func calculateFingerPrint(modulus: Data) -> Data? {
        guard modulus.count == 256 else { return nil } // 2048 bits

        // Reverse modulus bytes (Windows compatibility)
        let reversedModulus = modulus.reversedBytes

        // SHA1 digest
        var digest = [UInt8](repeating: 0, count: Int(CC_SHA1_DIGEST_LENGTH) + 4)
        reversedModulus.withUnsafeBytes { ptr in
            _ = CC_SHA1(ptr.baseAddress, CC_LONG(reversedModulus.count), &digest)
        }

        // Reverse first 20 bytes of digest
        var reversed = digest
        for i in 0..<Int(CC_SHA1_DIGEST_LENGTH) {
            reversed[i] = digest[Int(CC_SHA1_DIGEST_LENGTH) - 1 - i]
        }

        // XOR three 8-byte blocks to get 8-byte fingerprint
        var fingerPrint = [UInt8](repeating: 0, count: 8)
        for i in 0..<8 {
            fingerPrint[i] = reversed[i] ^ reversed[i + 8] ^ reversed[i + 16]
        }

        return Data(fingerPrint)
    }

    // MARK: - Message Encryption Flow
    // Ported from MessageCenter.m:1350-1496

    func encryptMessage(
        message: String,
        option: String?,
        packetNo: Int,
        recipientKey: RSAPublicKeyInfo,
        capability: CryptoCapability,
        supportsEncExtMsg: Bool,
        useUTF8: Bool
    ) -> EncryptionResult? {
        let useBase64 = capability.supportEncodeBase64
        var spec: UInt32 = 0

        if useBase64 {
            spec |= IPMsgEncFlag.encodeBase64.rawValue
        }

        // Build plaintext data
        guard let msgData = StringEncoding.encode(string: message, utf8: useUTF8, nullTerminate: true) else {
            return nil
        }

        var srcData = msgData
        var plainOptionData: Data?
        var encExtMsg = false

        if let option {
            let optData = StringEncoding.encode(string: option, utf8: useUTF8, nullTerminate: true)
            if supportsEncExtMsg, let optData {
                // Encrypt option as part of message body
                srcData = msgData + optData
                encExtMsg = true
            } else {
                plainOptionData = optData
            }
        }

        // Create IV
        var ivBytes = [UInt8](repeating: 0, count: 32)
        if capability.supportPacketNoIV {
            let ivString = "\(packetNo)"
            let ivData = Array(ivString.utf8)
            for i in 0..<min(ivData.count, 31) {
                ivBytes[i] = ivData[i]
            }
            spec |= IPMsgEncFlag.packetNoIV.rawValue
        }
        let ivData = Data(ivBytes)

        // Encrypt body
        var sessionKey: Data?
        var encryptedData: Data?

        NSLog("[CRYPTO] encryptMessage: recipientKeyBits=%d supportAES256=%d supportBlowfish=%d supportRSA2048=%d supportRSA1024=%d", recipientKey.keySizeInBits, capability.supportAES256 ? 1 : 0, capability.supportBlowfish128 ? 1 : 0, capability.supportRSA2048 ? 1 : 0, capability.supportRSA1024 ? 1 : 0)

        if capability.supportAES256 {
            sessionKey = randomData(byteCount: 32) // 256 bits
            guard let sk = sessionKey else { return nil }
            encryptedData = SymmetricCrypto.encrypt(data: srcData, key: sk, iv: ivData, algorithm: .aes256)
            guard encryptedData != nil else {
                NSLog("[CRYPTO] encryptMessage: AES-256 encryption FAILED")
                return nil
            }
            spec |= IPMsgEncFlag.aes256.rawValue
            NSLog("[CRYPTO] encryptMessage: body encrypted with AES-256 (srcData=%d bytes → encData=%d bytes)", srcData.count, encryptedData!.count)
        } else if capability.supportBlowfish128 {
            sessionKey = randomData(byteCount: 16) // 128 bits
            guard let sk = sessionKey else { return nil }
            encryptedData = SymmetricCrypto.encrypt(data: srcData, key: sk, iv: ivData, algorithm: .blowfish128)
            guard encryptedData != nil else {
                NSLog("[CRYPTO] encryptMessage: Blowfish-128 encryption FAILED")
                return nil
            }
            spec |= IPMsgEncFlag.blowfish128.rawValue
            NSLog("[CRYPTO] encryptMessage: body encrypted with Blowfish-128 (srcData=%d bytes → encData=%d bytes)", srcData.count, encryptedData!.count)
        }

        guard let sessionKey, let encryptedData else {
            NSLog("[CRYPTO] encryptMessage: no symmetric algorithm matched — cannot encrypt")
            return nil
        }

        // Encrypt session key with RSA
        NSLog("[CRYPTO] encryptMessage: encrypting %d-byte session key with recipient RSA%d key (mod=%d bytes)", sessionKey.count, recipientKey.keySizeInBits, recipientKey.modulus.count)
        guard let encryptedKey = encryptRSA(data: sessionKey, recipientKey: recipientKey) else {
            NSLog("[CRYPTO] encryptMessage: RSA session key encryption FAILED")
            return nil
        }
        NSLog("[CRYPTO] encryptMessage: session key RSA-encrypted OK (%d bytes)", encryptedKey.count)

        if recipientKey.keySizeInBits == 2048 {
            spec |= IPMsgEncFlag.rsa2048.rawValue
        } else {
            spec |= IPMsgEncFlag.rsa1024.rawValue
        }

        // Sign — prefer 2048-bit key for signing (matches original ipmsg behavior)
        let signKeyBitSize = (privateKey2048 != nil) ? 2048 : 1024
        var signData: Data?
        if capability.supportSignSHA256 {
            signData = signSHA256(data: msgData, keyBitSize: signKeyBitSize)
            if signData != nil {
                spec |= IPMsgEncFlag.signSHA256.rawValue
            }
        } else if capability.supportSignSHA1 {
            signData = signSHA1(data: msgData, keyBitSize: signKeyBitSize)
            if signData != nil {
                spec |= IPMsgEncFlag.signSHA1.rawValue
            }
        }

        // Build encrypted appendix: "spec:encKey:encBody[:signature]"
        var appendix = String(format: "%X:", spec)
        appendix += encryptedKey.binaryEncodedString(base64: useBase64)
        appendix += ":"
        appendix += encryptedData.binaryEncodedString(base64: useBase64)
        if let signData {
            appendix += ":"
            appendix += signData.binaryEncodedString(base64: useBase64)
        }

        return EncryptionResult(
            encryptedAppendix: appendix,
            plainOptionData: (encExtMsg ? nil : plainOptionData),
            encExtMsg: encExtMsg
        )
    }

    // MARK: - Message Decryption Flow
    // Ported from MessageCenter.m:1868-1997

    func decryptMessage(
        appendix: String,
        packetNo: Int,
        senderPublicKey: RSAPublicKeyInfo?,
        useUTF8: Bool
    ) -> DecryptionResult? {
        let components = appendix.components(separatedBy: ":")
        guard components.count >= 3 else {
            NSLog("[CRYPTO] Decrypt: appendix has %d components, need >= 3", components.count)
            return nil
        }

        // Parse capability spec
        guard let capa = UInt32(components[0], radix: 16) else {
            NSLog("[CRYPTO] Decrypt: invalid capability spec '%@'", components[0])
            return nil
        }
        let useBase64 = (capa & IPMsgEncFlag.encodeBase64.rawValue) != 0
        NSLog("[CRYPTO] Decrypt: spec=0x%08X base64=%d encKeyLen=%d encBodyLen=%d", capa, useBase64 ? 1 : 0, components[1].count, components[2].count)

        // Decrypt session key
        guard let encKey = Data(binaryEncodedString: components[1], base64: useBase64) else {
            NSLog("[CRYPTO] Decrypt: failed to decode encrypted session key (%@, len=%d)", useBase64 ? "base64" : "hex", components[1].count)
            return nil
        }

        // Determine expected session key size from symmetric algorithm in spec
        let expectedSessionKeySize: Int
        if (capa & IPMsgEncFlag.aes256.rawValue) != 0 {
            expectedSessionKeySize = 32 // AES-256
        } else if (capa & IPMsgEncFlag.blowfish128.rawValue) != 0 {
            expectedSessionKeySize = 16 // Blowfish-128
        } else {
            expectedSessionKeySize = 0 // unknown
        }

        // Try RSA decryption — with fallback to other key size if session key size is wrong
        var sessionKey: Data?
        let specSaysRSA2048 = (capa & IPMsgEncFlag.rsa2048.rawValue) != 0
        let specSaysRSA1024 = (capa & IPMsgEncFlag.rsa1024.rawValue) != 0

        // First attempt: use the key size from the spec
        let primaryKeySize: Int = specSaysRSA2048 ? 2048 : (specSaysRSA1024 ? 1024 : 0)
        let fallbackKeySize: Int = (primaryKeySize == 2048) ? 1024 : 2048

        if primaryKeySize > 0 {
            NSLog("[CRYPTO] Decrypt: trying RSA%d (from spec), encKey=%d bytes, havePriv2048=%d havePriv1024=%d", primaryKeySize, encKey.count, privateKey2048 != nil ? 1 : 0, privateKey1024 != nil ? 1 : 0)
            sessionKey = decryptRSA(data: encKey, keyBitSize: primaryKeySize)

            // Validate session key size — if wrong, RSA decryption used wrong key (implicit rejection returned garbage)
            if let sk = sessionKey, expectedSessionKeySize > 0, sk.count != expectedSessionKeySize {
                NSLog("[CRYPTO] Decrypt: RSA%d produced %d-byte session key, expected %d — wrong key! Trying RSA%d fallback...", primaryKeySize, sk.count, expectedSessionKeySize, fallbackKeySize)
                sessionKey = nil // discard garbage
                // RSA key size constrains ciphertext size: RSA1024 → 128 bytes, RSA2048 → 256 bytes.
                // Only attempt fallback if the ciphertext is the right size for the fallback key.
                let fallbackCompatible = (fallbackKeySize == 1024 && encKey.count == 128) ||
                                         (fallbackKeySize == 2048 && encKey.count == 256)
                if fallbackCompatible {
                    sessionKey = decryptRSA(data: encKey, keyBitSize: fallbackKeySize)
                    if let sk2 = sessionKey, sk2.count != expectedSessionKeySize {
                        NSLog("[CRYPTO] Decrypt: RSA%d fallback also produced %d-byte session key, expected %d — both keys wrong!", fallbackKeySize, sk2.count, expectedSessionKeySize)
                        sessionKey = nil
                    } else if sessionKey != nil {
                        NSLog("[CRYPTO] Decrypt: RSA%d fallback succeeded! Session key is %d bytes", fallbackKeySize, sessionKey!.count)
                    }
                } else {
                    NSLog("[CRYPTO] Decrypt: RSA%d fallback skipped — encKey is %d bytes, incompatible with RSA%d (needs %d bytes)", fallbackKeySize, encKey.count, fallbackKeySize, fallbackKeySize == 1024 ? 128 : 256)
                }
            }
        }

        // If spec had no RSA flag or primary failed without producing data, try both
        if sessionKey == nil && primaryKeySize == 0 {
            NSLog("[CRYPTO] Decrypt: no RSA flag in spec, trying RSA2048 then RSA1024")
            sessionKey = decryptRSA(data: encKey, keyBitSize: 2048)
            if let sk = sessionKey, expectedSessionKeySize > 0, sk.count != expectedSessionKeySize {
                sessionKey = nil
            }
            if sessionKey == nil {
                sessionKey = decryptRSA(data: encKey, keyBitSize: 1024)
                if let sk = sessionKey, expectedSessionKeySize > 0, sk.count != expectedSessionKeySize {
                    sessionKey = nil
                }
            }
        }

        guard let sessionKey else {
            NSLog("[CRYPTO] Decrypt: RSA session key decryption FAILED! encKey=%d bytes, expectedSessionKey=%d bytes. Private key may not match sender's cached public key.", encKey.count, expectedSessionKeySize)
            return nil
        }
        NSLog("[CRYPTO] Decrypt: session key decrypted OK (%d bytes)", sessionKey.count)

        // Create IV
        var ivBytes = [UInt8](repeating: 0, count: 32)
        if (capa & IPMsgEncFlag.packetNoIV.rawValue) != 0 {
            let ivString = "\(packetNo)"
            let ivData = Array(ivString.utf8)
            for i in 0..<min(ivData.count, 31) {
                ivBytes[i] = ivData[i]
            }
        }
        let ivData = Data(ivBytes)

        // Decrypt message body
        guard let encMsg = Data(binaryEncodedString: components[2], base64: useBase64) else {
            NSLog("[CRYPTO] Decrypt: failed to decode encrypted message body (%@, len=%d)", useBase64 ? "base64" : "hex", components[2].count)
            return nil
        }

        var messageData: Data?
        if (capa & IPMsgEncFlag.aes256.rawValue) != 0 {
            messageData = SymmetricCrypto.decrypt(data: encMsg, key: sessionKey, iv: ivData, algorithm: .aes256)
        } else if (capa & IPMsgEncFlag.blowfish128.rawValue) != 0 {
            messageData = SymmetricCrypto.decrypt(data: encMsg, key: sessionKey, iv: ivData, algorithm: .blowfish128)
        } else {
            NSLog("[CRYPTO] Decrypt: no recognized symmetric cipher in spec 0x%08X", capa)
        }
        guard let messageData else {
            NSLog("[CRYPTO] Decrypt: symmetric decryption failed (AES/Blowfish). encMsg=%d bytes, key=%d bytes", encMsg.count, sessionKey.count)
            return nil
        }

        // Verify signature — signature covers message body only (up to first NULL),
        // NOT the option data that may be appended when encExtMsg is used
        var doubt = false
        if components.count >= 4, (capa & (IPMsgEncFlag.signSHA1.rawValue | IPMsgEncFlag.signSHA256.rawValue)) != 0 {
            if let signature = Data(binaryEncodedString: components[3], base64: useBase64),
               let pubKey = senderPublicKey {
                // Extract message-only portion for verification (includes NULL terminator)
                let verifyData: Data
                if let nullIndex = messageData.firstIndex(of: 0) {
                    verifyData = messageData[messageData.startIndex...nullIndex]
                } else {
                    verifyData = messageData
                }
                if (capa & IPMsgEncFlag.signSHA256.rawValue) != 0 {
                    if !verifySHA256(signature: signature, data: verifyData, key: pubKey) {
                        doubt = true
                    }
                } else {
                    if !verifySHA1(signature: signature, data: verifyData, key: pubKey) {
                        doubt = true
                    }
                }
            }
        }

        // Extract plain text and option data
        let plainText = StringEncoding.decode(data: messageData, utf8: useUTF8) ?? ""

        // Check for encrypted option data (after NULL in message data)
        var optionData: Data?
        if let nullIndex = messageData.firstIndex(of: 0) {
            let afterNull = messageData.index(after: nullIndex)
            if afterNull < messageData.endIndex {
                optionData = messageData[afterNull...]
            }
        }

        // Determine secure level
        let secureLevel: Int
        if (capa & IPMsgEncFlag.rsa2048.rawValue) != 0 && (capa & IPMsgEncFlag.aes256.rawValue) != 0 {
            if (capa & IPMsgEncFlag.signSHA256.rawValue) != 0 {
                secureLevel = 4
            } else if (capa & IPMsgEncFlag.signSHA1.rawValue) != 0 {
                secureLevel = 3
            } else {
                secureLevel = 2
            }
        } else if (capa & IPMsgEncFlag.rsa1024.rawValue) != 0 && (capa & IPMsgEncFlag.blowfish128.rawValue) != 0 {
            secureLevel = 1
        } else {
            secureLevel = 0
        }

        return DecryptionResult(
            plainText: plainText,
            secureLevel: secureLevel,
            doubt: doubt,
            optionData: optionData
        )
    }
}
