// IPMsgX/Views/EmojiData.swift
// Curated emoji dataset for the built-in emoji picker

import Foundation

struct EmojiItem: Identifiable {
    let id = UUID()
    let emoji: String
    let name: String
}

struct EmojiCategory: Identifiable {
    let id = UUID()
    let name: String
    let icon: String   // emoji used as the tab icon
    let items: [EmojiItem]
}

enum EmojiData {
    static let categories: [EmojiCategory] = [
        EmojiCategory(name: "Smileys", icon: "😀", items: [
            EmojiItem(emoji: "😀", name: "grinning"),
            EmojiItem(emoji: "😃", name: "smiley"),
            EmojiItem(emoji: "😄", name: "smile"),
            EmojiItem(emoji: "😁", name: "grin"),
            EmojiItem(emoji: "😆", name: "laughing"),
            EmojiItem(emoji: "😅", name: "sweat smile"),
            EmojiItem(emoji: "🤣", name: "rofl"),
            EmojiItem(emoji: "😂", name: "joy"),
            EmojiItem(emoji: "🙂", name: "slightly smiling"),
            EmojiItem(emoji: "🙃", name: "upside down"),
            EmojiItem(emoji: "😉", name: "winking"),
            EmojiItem(emoji: "😊", name: "blush"),
            EmojiItem(emoji: "😇", name: "innocent"),
            EmojiItem(emoji: "🥰", name: "smiling hearts"),
            EmojiItem(emoji: "😍", name: "heart eyes"),
            EmojiItem(emoji: "🤩", name: "star struck"),
            EmojiItem(emoji: "😘", name: "kissing heart"),
            EmojiItem(emoji: "😗", name: "kissing"),
            EmojiItem(emoji: "😋", name: "yum"),
            EmojiItem(emoji: "😛", name: "tongue"),
            EmojiItem(emoji: "😜", name: "winking tongue"),
            EmojiItem(emoji: "🤪", name: "zany"),
            EmojiItem(emoji: "😝", name: "squinting tongue"),
            EmojiItem(emoji: "🤑", name: "money mouth"),
            EmojiItem(emoji: "🤗", name: "hugging"),
            EmojiItem(emoji: "🤔", name: "thinking"),
            EmojiItem(emoji: "🤐", name: "zipper mouth"),
            EmojiItem(emoji: "😐", name: "neutral"),
            EmojiItem(emoji: "😑", name: "expressionless"),
            EmojiItem(emoji: "😶", name: "no mouth"),
            EmojiItem(emoji: "😏", name: "smirking"),
            EmojiItem(emoji: "😒", name: "unamused"),
            EmojiItem(emoji: "🙄", name: "eye roll"),
            EmojiItem(emoji: "😬", name: "grimacing"),
            EmojiItem(emoji: "🤥", name: "lying"),
            EmojiItem(emoji: "😌", name: "relieved"),
            EmojiItem(emoji: "😔", name: "pensive"),
            EmojiItem(emoji: "😪", name: "sleepy"),
            EmojiItem(emoji: "😴", name: "sleeping"),
            EmojiItem(emoji: "🤤", name: "drooling"),
            EmojiItem(emoji: "😷", name: "mask"),
            EmojiItem(emoji: "🤒", name: "thermometer face"),
            EmojiItem(emoji: "🤕", name: "bandage face"),
            EmojiItem(emoji: "🤢", name: "nauseated"),
            EmojiItem(emoji: "🤮", name: "vomiting"),
            EmojiItem(emoji: "🤧", name: "sneezing"),
            EmojiItem(emoji: "🥵", name: "hot"),
            EmojiItem(emoji: "🥶", name: "cold"),
            EmojiItem(emoji: "😵", name: "dizzy face"),
            EmojiItem(emoji: "🤯", name: "exploding head"),
            EmojiItem(emoji: "🤠", name: "cowboy"),
            EmojiItem(emoji: "🥳", name: "partying"),
            EmojiItem(emoji: "😎", name: "sunglasses"),
            EmojiItem(emoji: "🤓", name: "nerd"),
            EmojiItem(emoji: "🧐", name: "monocle"),
            EmojiItem(emoji: "😕", name: "confused"),
            EmojiItem(emoji: "😟", name: "worried"),
            EmojiItem(emoji: "🙁", name: "slightly frowning"),
            EmojiItem(emoji: "☹️", name: "frowning"),
            EmojiItem(emoji: "😮", name: "open mouth"),
            EmojiItem(emoji: "😲", name: "astonished"),
            EmojiItem(emoji: "😳", name: "flushed"),
            EmojiItem(emoji: "🥺", name: "pleading"),
            EmojiItem(emoji: "😦", name: "frowning open"),
            EmojiItem(emoji: "😧", name: "anguished"),
            EmojiItem(emoji: "😨", name: "fearful"),
            EmojiItem(emoji: "😰", name: "anxious sweat"),
            EmojiItem(emoji: "😥", name: "sad sweat"),
            EmojiItem(emoji: "😢", name: "crying"),
            EmojiItem(emoji: "😭", name: "loudly crying"),
            EmojiItem(emoji: "😱", name: "screaming fear"),
            EmojiItem(emoji: "😖", name: "confounded"),
            EmojiItem(emoji: "😣", name: "persevering"),
            EmojiItem(emoji: "😞", name: "disappointed"),
            EmojiItem(emoji: "😓", name: "downcast sweat"),
            EmojiItem(emoji: "😩", name: "weary"),
            EmojiItem(emoji: "😫", name: "tired"),
            EmojiItem(emoji: "😤", name: "huffing"),
            EmojiItem(emoji: "😡", name: "pouting"),
            EmojiItem(emoji: "😠", name: "angry"),
            EmojiItem(emoji: "🤬", name: "cursing"),
            EmojiItem(emoji: "👿", name: "angry devil"),
            EmojiItem(emoji: "💀", name: "skull"),
            EmojiItem(emoji: "☠️", name: "skull crossbones"),
            EmojiItem(emoji: "💩", name: "poop"),
            EmojiItem(emoji: "🤡", name: "clown"),
            EmojiItem(emoji: "👹", name: "ogre"),
            EmojiItem(emoji: "👺", name: "goblin"),
            EmojiItem(emoji: "👻", name: "ghost"),
            EmojiItem(emoji: "👽", name: "alien"),
            EmojiItem(emoji: "👾", name: "space invader"),
            EmojiItem(emoji: "🤖", name: "robot"),
        ]),

        EmojiCategory(name: "People", icon: "👋", items: [
            EmojiItem(emoji: "👋", name: "wave"),
            EmojiItem(emoji: "🤚", name: "raised back hand"),
            EmojiItem(emoji: "🖐️", name: "raised hand"),
            EmojiItem(emoji: "✋", name: "stop hand"),
            EmojiItem(emoji: "🖖", name: "vulcan salute"),
            EmojiItem(emoji: "👌", name: "ok hand"),
            EmojiItem(emoji: "🤌", name: "pinched fingers"),
            EmojiItem(emoji: "✌️", name: "victory"),
            EmojiItem(emoji: "🤞", name: "crossed fingers"),
            EmojiItem(emoji: "🤟", name: "love you"),
            EmojiItem(emoji: "🤘", name: "rock on"),
            EmojiItem(emoji: "🤙", name: "call me"),
            EmojiItem(emoji: "👈", name: "pointing left"),
            EmojiItem(emoji: "👉", name: "pointing right"),
            EmojiItem(emoji: "👆", name: "pointing up"),
            EmojiItem(emoji: "🖕", name: "middle finger"),
            EmojiItem(emoji: "👇", name: "pointing down"),
            EmojiItem(emoji: "☝️", name: "index up"),
            EmojiItem(emoji: "👍", name: "thumbs up"),
            EmojiItem(emoji: "👎", name: "thumbs down"),
            EmojiItem(emoji: "✊", name: "raised fist"),
            EmojiItem(emoji: "👊", name: "oncoming fist"),
            EmojiItem(emoji: "🤛", name: "left fist"),
            EmojiItem(emoji: "🤜", name: "right fist"),
            EmojiItem(emoji: "👏", name: "clapping"),
            EmojiItem(emoji: "🙌", name: "raised hands"),
            EmojiItem(emoji: "👐", name: "open hands"),
            EmojiItem(emoji: "🤲", name: "palms up"),
            EmojiItem(emoji: "🤝", name: "handshake"),
            EmojiItem(emoji: "🙏", name: "folded hands pray"),
            EmojiItem(emoji: "💪", name: "muscle flexed"),
            EmojiItem(emoji: "🦾", name: "mechanical arm"),
            EmojiItem(emoji: "🦿", name: "mechanical leg"),
            EmojiItem(emoji: "💋", name: "kiss mark"),
            EmojiItem(emoji: "💌", name: "love letter"),
            EmojiItem(emoji: "👀", name: "eyes"),
            EmojiItem(emoji: "👁️", name: "eye"),
            EmojiItem(emoji: "👅", name: "tongue"),
            EmojiItem(emoji: "👄", name: "mouth lips"),
            EmojiItem(emoji: "🫀", name: "heart organ"),
            EmojiItem(emoji: "🫁", name: "lungs"),
            EmojiItem(emoji: "🧠", name: "brain"),
            EmojiItem(emoji: "👶", name: "baby"),
            EmojiItem(emoji: "👦", name: "boy"),
            EmojiItem(emoji: "👧", name: "girl"),
            EmojiItem(emoji: "🧑", name: "person"),
            EmojiItem(emoji: "👱", name: "blond person"),
            EmojiItem(emoji: "👨", name: "man"),
            EmojiItem(emoji: "👩", name: "woman"),
            EmojiItem(emoji: "🧓", name: "older person"),
            EmojiItem(emoji: "👴", name: "old man"),
            EmojiItem(emoji: "👵", name: "old woman"),
        ]),

        EmojiCategory(name: "Animals", icon: "🐶", items: [
            EmojiItem(emoji: "🐶", name: "dog"),
            EmojiItem(emoji: "🐱", name: "cat"),
            EmojiItem(emoji: "🐭", name: "mouse"),
            EmojiItem(emoji: "🐹", name: "hamster"),
            EmojiItem(emoji: "🐰", name: "rabbit"),
            EmojiItem(emoji: "🦊", name: "fox"),
            EmojiItem(emoji: "🐻", name: "bear"),
            EmojiItem(emoji: "🐼", name: "panda"),
            EmojiItem(emoji: "🐨", name: "koala"),
            EmojiItem(emoji: "🐯", name: "tiger"),
            EmojiItem(emoji: "🦁", name: "lion"),
            EmojiItem(emoji: "🐮", name: "cow"),
            EmojiItem(emoji: "🐷", name: "pig"),
            EmojiItem(emoji: "🐸", name: "frog"),
            EmojiItem(emoji: "🐵", name: "monkey"),
            EmojiItem(emoji: "🙈", name: "see no evil"),
            EmojiItem(emoji: "🙉", name: "hear no evil"),
            EmojiItem(emoji: "🙊", name: "speak no evil"),
            EmojiItem(emoji: "🐔", name: "chicken"),
            EmojiItem(emoji: "🐧", name: "penguin"),
            EmojiItem(emoji: "🐦", name: "bird"),
            EmojiItem(emoji: "🦆", name: "duck"),
            EmojiItem(emoji: "🦅", name: "eagle"),
            EmojiItem(emoji: "🦉", name: "owl"),
            EmojiItem(emoji: "🦇", name: "bat"),
            EmojiItem(emoji: "🐺", name: "wolf"),
            EmojiItem(emoji: "🐗", name: "boar"),
            EmojiItem(emoji: "🐴", name: "horse"),
            EmojiItem(emoji: "🦄", name: "unicorn"),
            EmojiItem(emoji: "🐝", name: "bee"),
            EmojiItem(emoji: "🦋", name: "butterfly"),
            EmojiItem(emoji: "🐌", name: "snail"),
            EmojiItem(emoji: "🐞", name: "ladybug"),
            EmojiItem(emoji: "🐜", name: "ant"),
            EmojiItem(emoji: "🐢", name: "turtle"),
            EmojiItem(emoji: "🐍", name: "snake"),
            EmojiItem(emoji: "🦎", name: "lizard"),
            EmojiItem(emoji: "🦈", name: "shark"),
            EmojiItem(emoji: "🐙", name: "octopus"),
            EmojiItem(emoji: "🦑", name: "squid"),
            EmojiItem(emoji: "🦀", name: "crab"),
            EmojiItem(emoji: "🐡", name: "blowfish"),
            EmojiItem(emoji: "🐟", name: "fish"),
            EmojiItem(emoji: "🐬", name: "dolphin"),
            EmojiItem(emoji: "🐳", name: "whale"),
            EmojiItem(emoji: "🦭", name: "seal"),
            EmojiItem(emoji: "🦘", name: "kangaroo"),
            EmojiItem(emoji: "🦒", name: "giraffe"),
            EmojiItem(emoji: "🦓", name: "zebra"),
            EmojiItem(emoji: "🐘", name: "elephant"),
            EmojiItem(emoji: "🦛", name: "hippo"),
            EmojiItem(emoji: "🦏", name: "rhino"),
            EmojiItem(emoji: "🦙", name: "llama"),
            EmojiItem(emoji: "🐐", name: "goat"),
            EmojiItem(emoji: "🦌", name: "deer"),
            EmojiItem(emoji: "🦔", name: "hedgehog"),
            EmojiItem(emoji: "🦡", name: "badger"),
            EmojiItem(emoji: "🦦", name: "otter"),
            EmojiItem(emoji: "🌸", name: "cherry blossom"),
            EmojiItem(emoji: "🌺", name: "hibiscus"),
            EmojiItem(emoji: "🌻", name: "sunflower"),
            EmojiItem(emoji: "🌹", name: "rose"),
            EmojiItem(emoji: "🌷", name: "tulip"),
            EmojiItem(emoji: "🌼", name: "blossom"),
            EmojiItem(emoji: "💐", name: "bouquet"),
            EmojiItem(emoji: "🍀", name: "four leaf clover"),
            EmojiItem(emoji: "🌿", name: "herb"),
            EmojiItem(emoji: "🌱", name: "seedling"),
            EmojiItem(emoji: "🌲", name: "evergreen tree"),
            EmojiItem(emoji: "🌳", name: "deciduous tree"),
            EmojiItem(emoji: "🌴", name: "palm tree"),
            EmojiItem(emoji: "🌵", name: "cactus"),
        ]),

        EmojiCategory(name: "Food", icon: "🍔", items: [
            EmojiItem(emoji: "🍎", name: "apple"),
            EmojiItem(emoji: "🍊", name: "orange"),
            EmojiItem(emoji: "🍋", name: "lemon"),
            EmojiItem(emoji: "🍌", name: "banana"),
            EmojiItem(emoji: "🍍", name: "pineapple"),
            EmojiItem(emoji: "🥭", name: "mango"),
            EmojiItem(emoji: "🍓", name: "strawberry"),
            EmojiItem(emoji: "🍒", name: "cherries"),
            EmojiItem(emoji: "🍑", name: "peach"),
            EmojiItem(emoji: "🥝", name: "kiwi"),
            EmojiItem(emoji: "🍅", name: "tomato"),
            EmojiItem(emoji: "🫐", name: "blueberries"),
            EmojiItem(emoji: "🥥", name: "coconut"),
            EmojiItem(emoji: "🥑", name: "avocado"),
            EmojiItem(emoji: "🍆", name: "eggplant"),
            EmojiItem(emoji: "🥔", name: "potato"),
            EmojiItem(emoji: "🥕", name: "carrot"),
            EmojiItem(emoji: "🌽", name: "corn"),
            EmojiItem(emoji: "🌶️", name: "hot pepper"),
            EmojiItem(emoji: "🥒", name: "cucumber"),
            EmojiItem(emoji: "🥦", name: "broccoli"),
            EmojiItem(emoji: "🍄", name: "mushroom"),
            EmojiItem(emoji: "🥜", name: "peanuts"),
            EmojiItem(emoji: "🍞", name: "bread"),
            EmojiItem(emoji: "🥐", name: "croissant"),
            EmojiItem(emoji: "🧀", name: "cheese"),
            EmojiItem(emoji: "🥚", name: "egg"),
            EmojiItem(emoji: "🥞", name: "pancakes"),
            EmojiItem(emoji: "🧇", name: "waffle"),
            EmojiItem(emoji: "🥓", name: "bacon"),
            EmojiItem(emoji: "🍗", name: "chicken leg"),
            EmojiItem(emoji: "🍔", name: "hamburger"),
            EmojiItem(emoji: "🍟", name: "fries"),
            EmojiItem(emoji: "🍕", name: "pizza"),
            EmojiItem(emoji: "🌮", name: "taco"),
            EmojiItem(emoji: "🌯", name: "burrito"),
            EmojiItem(emoji: "🍜", name: "noodles"),
            EmojiItem(emoji: "🍣", name: "sushi"),
            EmojiItem(emoji: "🍱", name: "bento box"),
            EmojiItem(emoji: "🍝", name: "spaghetti"),
            EmojiItem(emoji: "🍲", name: "pot of food"),
            EmojiItem(emoji: "🍛", name: "curry"),
            EmojiItem(emoji: "🥗", name: "salad"),
            EmojiItem(emoji: "🍰", name: "cake"),
            EmojiItem(emoji: "🎂", name: "birthday cake"),
            EmojiItem(emoji: "🧁", name: "cupcake"),
            EmojiItem(emoji: "🍩", name: "donut"),
            EmojiItem(emoji: "🍪", name: "cookie"),
            EmojiItem(emoji: "🍫", name: "chocolate"),
            EmojiItem(emoji: "🍬", name: "candy"),
            EmojiItem(emoji: "🍭", name: "lollipop"),
            EmojiItem(emoji: "🍦", name: "ice cream"),
            EmojiItem(emoji: "🧃", name: "juice box"),
            EmojiItem(emoji: "☕", name: "coffee"),
            EmojiItem(emoji: "🍵", name: "tea"),
            EmojiItem(emoji: "🧋", name: "bubble tea"),
            EmojiItem(emoji: "🥤", name: "cup with straw"),
            EmojiItem(emoji: "🍺", name: "beer"),
            EmojiItem(emoji: "🍷", name: "wine"),
            EmojiItem(emoji: "🥂", name: "champagne"),
            EmojiItem(emoji: "🍸", name: "cocktail"),
            EmojiItem(emoji: "🥃", name: "whiskey"),
            EmojiItem(emoji: "🍾", name: "champagne bottle"),
        ]),

        EmojiCategory(name: "Travel", icon: "✈️", items: [
            EmojiItem(emoji: "✈️", name: "airplane"),
            EmojiItem(emoji: "🚀", name: "rocket"),
            EmojiItem(emoji: "🛸", name: "ufo"),
            EmojiItem(emoji: "🚁", name: "helicopter"),
            EmojiItem(emoji: "🚗", name: "car"),
            EmojiItem(emoji: "🚕", name: "taxi"),
            EmojiItem(emoji: "🚙", name: "suv"),
            EmojiItem(emoji: "🚌", name: "bus"),
            EmojiItem(emoji: "🏎️", name: "racing car"),
            EmojiItem(emoji: "🚓", name: "police car"),
            EmojiItem(emoji: "🚑", name: "ambulance"),
            EmojiItem(emoji: "🚒", name: "fire truck"),
            EmojiItem(emoji: "🚚", name: "delivery truck"),
            EmojiItem(emoji: "🏍️", name: "motorcycle"),
            EmojiItem(emoji: "🛵", name: "scooter"),
            EmojiItem(emoji: "🚲", name: "bicycle"),
            EmojiItem(emoji: "🛴", name: "kick scooter"),
            EmojiItem(emoji: "⛵", name: "sailboat"),
            EmojiItem(emoji: "🚤", name: "speedboat"),
            EmojiItem(emoji: "🚢", name: "ship"),
            EmojiItem(emoji: "🗺️", name: "world map"),
            EmojiItem(emoji: "🧭", name: "compass"),
            EmojiItem(emoji: "🏔️", name: "mountain snow"),
            EmojiItem(emoji: "⛰️", name: "mountain"),
            EmojiItem(emoji: "🌋", name: "volcano"),
            EmojiItem(emoji: "🏕️", name: "camping"),
            EmojiItem(emoji: "🏖️", name: "beach"),
            EmojiItem(emoji: "🏜️", name: "desert"),
            EmojiItem(emoji: "🏝️", name: "island"),
            EmojiItem(emoji: "🏠", name: "house"),
            EmojiItem(emoji: "🏢", name: "office building"),
            EmojiItem(emoji: "🏥", name: "hospital"),
            EmojiItem(emoji: "🏦", name: "bank"),
            EmojiItem(emoji: "🏨", name: "hotel"),
            EmojiItem(emoji: "🏪", name: "convenience store"),
            EmojiItem(emoji: "🏫", name: "school"),
            EmojiItem(emoji: "🏰", name: "castle"),
            EmojiItem(emoji: "⛪", name: "church"),
            EmojiItem(emoji: "🗼", name: "tokyo tower"),
            EmojiItem(emoji: "🗽", name: "statue of liberty"),
            EmojiItem(emoji: "🌍", name: "globe africa europe"),
            EmojiItem(emoji: "🌎", name: "globe americas"),
            EmojiItem(emoji: "🌏", name: "globe asia"),
            EmojiItem(emoji: "🌐", name: "globe meridians"),
            EmojiItem(emoji: "🌁", name: "foggy"),
            EmojiItem(emoji: "🌃", name: "night with stars"),
            EmojiItem(emoji: "🏙️", name: "cityscape"),
            EmojiItem(emoji: "🌄", name: "sunrise mountains"),
            EmojiItem(emoji: "🌅", name: "sunrise"),
            EmojiItem(emoji: "🌉", name: "bridge at night"),
            EmojiItem(emoji: "🌌", name: "milky way"),
            EmojiItem(emoji: "☀️", name: "sun"),
            EmojiItem(emoji: "🌙", name: "crescent moon"),
            EmojiItem(emoji: "⭐", name: "star"),
            EmojiItem(emoji: "🌟", name: "glowing star"),
            EmojiItem(emoji: "✨", name: "sparkles"),
            EmojiItem(emoji: "⛅", name: "partly cloudy"),
            EmojiItem(emoji: "🌧️", name: "rain"),
            EmojiItem(emoji: "⛈️", name: "storm"),
            EmojiItem(emoji: "🌩️", name: "lightning"),
            EmojiItem(emoji: "❄️", name: "snowflake"),
            EmojiItem(emoji: "🌈", name: "rainbow"),
        ]),

        EmojiCategory(name: "Activities", icon: "⚽", items: [
            EmojiItem(emoji: "⚽", name: "soccer ball"),
            EmojiItem(emoji: "🏀", name: "basketball"),
            EmojiItem(emoji: "🏈", name: "american football"),
            EmojiItem(emoji: "⚾", name: "baseball"),
            EmojiItem(emoji: "🥎", name: "softball"),
            EmojiItem(emoji: "🏐", name: "volleyball"),
            EmojiItem(emoji: "🏉", name: "rugby"),
            EmojiItem(emoji: "🎾", name: "tennis"),
            EmojiItem(emoji: "🏸", name: "badminton"),
            EmojiItem(emoji: "🏒", name: "ice hockey"),
            EmojiItem(emoji: "🏓", name: "ping pong"),
            EmojiItem(emoji: "🥊", name: "boxing glove"),
            EmojiItem(emoji: "🥋", name: "martial arts"),
            EmojiItem(emoji: "🎽", name: "running shirt"),
            EmojiItem(emoji: "⛷️", name: "skiing"),
            EmojiItem(emoji: "🏂", name: "snowboarding"),
            EmojiItem(emoji: "🏋️", name: "weight lifting"),
            EmojiItem(emoji: "🤸", name: "gymnastics"),
            EmojiItem(emoji: "🏊", name: "swimming"),
            EmojiItem(emoji: "🚴", name: "cycling"),
            EmojiItem(emoji: "🏆", name: "trophy"),
            EmojiItem(emoji: "🥇", name: "gold medal"),
            EmojiItem(emoji: "🥈", name: "silver medal"),
            EmojiItem(emoji: "🥉", name: "bronze medal"),
            EmojiItem(emoji: "🎯", name: "bullseye"),
            EmojiItem(emoji: "🎳", name: "bowling"),
            EmojiItem(emoji: "🎮", name: "video game controller"),
            EmojiItem(emoji: "🕹️", name: "joystick"),
            EmojiItem(emoji: "🎲", name: "dice"),
            EmojiItem(emoji: "♟️", name: "chess pawn"),
            EmojiItem(emoji: "🧩", name: "puzzle piece"),
            EmojiItem(emoji: "🎭", name: "performing arts"),
            EmojiItem(emoji: "🎨", name: "artist palette"),
            EmojiItem(emoji: "🖼️", name: "framed picture"),
            EmojiItem(emoji: "🎪", name: "circus tent"),
            EmojiItem(emoji: "🤹", name: "juggling"),
            EmojiItem(emoji: "🎵", name: "music note"),
            EmojiItem(emoji: "🎶", name: "music notes"),
            EmojiItem(emoji: "🎸", name: "guitar"),
            EmojiItem(emoji: "🎹", name: "piano keyboard"),
            EmojiItem(emoji: "🎷", name: "saxophone"),
            EmojiItem(emoji: "🎺", name: "trumpet"),
            EmojiItem(emoji: "🎻", name: "violin"),
            EmojiItem(emoji: "🥁", name: "drum"),
            EmojiItem(emoji: "🎤", name: "microphone"),
            EmojiItem(emoji: "🎧", name: "headphones"),
            EmojiItem(emoji: "🎬", name: "clapperboard"),
            EmojiItem(emoji: "📷", name: "camera"),
            EmojiItem(emoji: "🎉", name: "party popper"),
            EmojiItem(emoji: "🎊", name: "confetti ball"),
            EmojiItem(emoji: "🎈", name: "balloon"),
            EmojiItem(emoji: "🎁", name: "gift"),
            EmojiItem(emoji: "🎀", name: "ribbon"),
        ]),

        EmojiCategory(name: "Objects", icon: "💡", items: [
            EmojiItem(emoji: "📱", name: "mobile phone"),
            EmojiItem(emoji: "💻", name: "laptop"),
            EmojiItem(emoji: "⌨️", name: "keyboard"),
            EmojiItem(emoji: "🖥️", name: "desktop computer"),
            EmojiItem(emoji: "🖨️", name: "printer"),
            EmojiItem(emoji: "🖱️", name: "computer mouse"),
            EmojiItem(emoji: "💾", name: "floppy disk"),
            EmojiItem(emoji: "💿", name: "optical disk"),
            EmojiItem(emoji: "📀", name: "dvd"),
            EmojiItem(emoji: "📞", name: "telephone"),
            EmojiItem(emoji: "☎️", name: "phone"),
            EmojiItem(emoji: "📺", name: "television"),
            EmojiItem(emoji: "📻", name: "radio"),
            EmojiItem(emoji: "🔋", name: "battery"),
            EmojiItem(emoji: "🔌", name: "electric plug"),
            EmojiItem(emoji: "💡", name: "light bulb"),
            EmojiItem(emoji: "🔦", name: "flashlight"),
            EmojiItem(emoji: "🕯️", name: "candle"),
            EmojiItem(emoji: "📚", name: "books"),
            EmojiItem(emoji: "📖", name: "open book"),
            EmojiItem(emoji: "📝", name: "memo"),
            EmojiItem(emoji: "📌", name: "pushpin"),
            EmojiItem(emoji: "📍", name: "round pushpin"),
            EmojiItem(emoji: "📎", name: "paperclip"),
            EmojiItem(emoji: "✂️", name: "scissors"),
            EmojiItem(emoji: "🗑️", name: "wastebasket"),
            EmojiItem(emoji: "🔒", name: "locked"),
            EmojiItem(emoji: "🔓", name: "unlocked"),
            EmojiItem(emoji: "🔑", name: "key"),
            EmojiItem(emoji: "🗝️", name: "old key"),
            EmojiItem(emoji: "🔨", name: "hammer"),
            EmojiItem(emoji: "🔧", name: "wrench"),
            EmojiItem(emoji: "🔩", name: "nut and bolt"),
            EmojiItem(emoji: "⚙️", name: "gear"),
            EmojiItem(emoji: "🧲", name: "magnet"),
            EmojiItem(emoji: "🧰", name: "toolbox"),
            EmojiItem(emoji: "🔍", name: "magnifying glass left"),
            EmojiItem(emoji: "🔬", name: "microscope"),
            EmojiItem(emoji: "🔭", name: "telescope"),
            EmojiItem(emoji: "💊", name: "pill"),
            EmojiItem(emoji: "💉", name: "syringe"),
            EmojiItem(emoji: "🩺", name: "stethoscope"),
            EmojiItem(emoji: "🩹", name: "bandage"),
            EmojiItem(emoji: "🧴", name: "lotion bottle"),
            EmojiItem(emoji: "🧹", name: "broom"),
            EmojiItem(emoji: "🧺", name: "basket"),
            EmojiItem(emoji: "🧼", name: "soap"),
            EmojiItem(emoji: "📦", name: "package"),
            EmojiItem(emoji: "📫", name: "mailbox"),
            EmojiItem(emoji: "💼", name: "briefcase"),
            EmojiItem(emoji: "👜", name: "handbag"),
            EmojiItem(emoji: "🎒", name: "backpack"),
            EmojiItem(emoji: "👑", name: "crown"),
            EmojiItem(emoji: "💍", name: "ring"),
            EmojiItem(emoji: "💎", name: "gem stone"),
            EmojiItem(emoji: "🧸", name: "teddy bear"),
            EmojiItem(emoji: "🔔", name: "bell"),
            EmojiItem(emoji: "🔕", name: "bell with slash"),
        ]),

        EmojiCategory(name: "Symbols", icon: "❤️", items: [
            EmojiItem(emoji: "❤️", name: "red heart"),
            EmojiItem(emoji: "🧡", name: "orange heart"),
            EmojiItem(emoji: "💛", name: "yellow heart"),
            EmojiItem(emoji: "💚", name: "green heart"),
            EmojiItem(emoji: "💙", name: "blue heart"),
            EmojiItem(emoji: "💜", name: "purple heart"),
            EmojiItem(emoji: "🖤", name: "black heart"),
            EmojiItem(emoji: "🤍", name: "white heart"),
            EmojiItem(emoji: "🤎", name: "brown heart"),
            EmojiItem(emoji: "💔", name: "broken heart"),
            EmojiItem(emoji: "❣️", name: "heart exclamation"),
            EmojiItem(emoji: "💕", name: "two hearts"),
            EmojiItem(emoji: "💞", name: "revolving hearts"),
            EmojiItem(emoji: "💓", name: "beating heart"),
            EmojiItem(emoji: "💗", name: "growing heart"),
            EmojiItem(emoji: "💖", name: "sparkling heart"),
            EmojiItem(emoji: "💘", name: "heart with arrow"),
            EmojiItem(emoji: "💝", name: "heart with ribbon"),
            EmojiItem(emoji: "❤️‍🔥", name: "heart on fire"),
            EmojiItem(emoji: "💬", name: "speech bubble"),
            EmojiItem(emoji: "💭", name: "thought bubble"),
            EmojiItem(emoji: "💢", name: "anger symbol"),
            EmojiItem(emoji: "💯", name: "hundred points"),
            EmojiItem(emoji: "✅", name: "check mark button"),
            EmojiItem(emoji: "❎", name: "cross mark button"),
            EmojiItem(emoji: "❌", name: "cross mark"),
            EmojiItem(emoji: "⭕", name: "hollow red circle"),
            EmojiItem(emoji: "🚫", name: "prohibited"),
            EmojiItem(emoji: "⛔", name: "no entry"),
            EmojiItem(emoji: "⚠️", name: "warning"),
            EmojiItem(emoji: "🔴", name: "red circle"),
            EmojiItem(emoji: "🟠", name: "orange circle"),
            EmojiItem(emoji: "🟡", name: "yellow circle"),
            EmojiItem(emoji: "🟢", name: "green circle"),
            EmojiItem(emoji: "🔵", name: "blue circle"),
            EmojiItem(emoji: "🟣", name: "purple circle"),
            EmojiItem(emoji: "⚫", name: "black circle"),
            EmojiItem(emoji: "⚪", name: "white circle"),
            EmojiItem(emoji: "🔥", name: "fire"),
            EmojiItem(emoji: "⚡", name: "lightning bolt"),
            EmojiItem(emoji: "💧", name: "droplet"),
            EmojiItem(emoji: "🌊", name: "wave"),
            EmojiItem(emoji: "💫", name: "dizzy star"),
            EmojiItem(emoji: "🌀", name: "cyclone"),
            EmojiItem(emoji: "🎯", name: "direct hit"),
            EmojiItem(emoji: "🔞", name: "no one under eighteen"),
            EmojiItem(emoji: "🆕", name: "new"),
            EmojiItem(emoji: "🆒", name: "cool"),
            EmojiItem(emoji: "🆓", name: "free"),
            EmojiItem(emoji: "🆗", name: "ok"),
            EmojiItem(emoji: "🆘", name: "sos"),
            EmojiItem(emoji: "♾️", name: "infinity"),
            EmojiItem(emoji: "☮️", name: "peace symbol"),
            EmojiItem(emoji: "❓", name: "question mark"),
            EmojiItem(emoji: "❗", name: "exclamation mark"),
            EmojiItem(emoji: "‼️", name: "double exclamation"),
            EmojiItem(emoji: "⁉️", name: "exclamation question"),
            EmojiItem(emoji: "🔊", name: "speaker loud"),
            EmojiItem(emoji: "🔇", name: "muted speaker"),
            EmojiItem(emoji: "📢", name: "loudspeaker"),
            EmojiItem(emoji: "📣", name: "megaphone"),
            EmojiItem(emoji: "🔔", name: "bell ringing"),
        ]),
    ]

    /// All emoji items flattened, for search
    static let allItems: [EmojiItem] = categories.flatMap { $0.items }
}
